const sample = [
['Science','What is the chemical symbol for gold?','Au'],['Maths','What is 12 × 12?','144'],['Logic','If all Bloops are Razzies and all Razzies are Lazzies, are all Bloops Lazzies?','Yes'],['Geography','What is the longest river in South America?','The Amazon River'],['History','Which wall fell in 1989?','The Berlin Wall'],['Technology','What does CPU stand for?','Central Processing Unit'],['General knowledge','How many sides does a hexagon have?','Six'],['Pop culture','Which fictional wizard has a lightning-shaped scar?','Harry Potter'],['Sports','How many players does a soccer team have on the pitch?','Eleven'],['Riddle','What has keys but cannot open locks?','A piano'],['Science','What planet is known as the Red Planet?','Mars'],['Maths','What is the square root of 81?','9'],['Logic','Which is heavier: a kilogram of feathers or a kilogram of bricks?','They weigh the same'],['Geography','What is the capital of Japan?','Tokyo'],['History','Who was the first person to walk on the Moon?','Neil Armstrong'],['Technology','What does URL stand for?','Uniform Resource Locator'],['General knowledge','What is the largest ocean on Earth?','The Pacific Ocean'],['Pop culture','In which franchise would you find a lightsaber?','Star Wars'],['Sports','In tennis, what is a score of zero called?','Love'],['Riddle','What gets wetter the more it dries?','A towel'],['Science','What gas do plants absorb from the atmosphere?','Carbon dioxide'],['Maths','How many degrees are in a right angle?','90'],['Logic','What comes next: 2, 6, 12, 20, 30?','42'],['Geography','Which country has the most pyramids?','Sudan'],['History','Which ancient civilization built Machu Picchu?','The Inca']
];
const defaults={teamA:'Solaris',teamB:'Orbit',size:5,line:4,questions:sample.map(([,text])=>({text})),claims:[],attempts:[],turn:0,selected:null,seconds:30,started:false,finished:false};
let state=structuredClone(defaults), interval;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function database(){return new Promise((resolve,reject)=>{let request=indexedDB.open('TriviaGridDatabase',1);request.onupgradeneeded=()=>request.result.createObjectStore('games');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function load(){try{let db=await database();return {...defaults,...(await new Promise((resolve,reject)=>{let request=db.transaction('games').objectStore('games').get('current');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)}))}}catch{return structuredClone(defaults)}}
function save(){database().then(db=>{let tx=db.transaction('games','readwrite');tx.objectStore('games').put(structuredClone(state),'current')}).catch(()=>{})}
async function loadSharedQuestions(){try{let response=await fetch('./questions.json',{cache:'no-store'});if(!response.ok)throw new Error('Question catalogue unavailable');let questions=await response.json();return questions.filter(q=>typeof q.text==='string'&&q.text.trim()).map(q=>({text:q.text.trim()}))}catch{return sample.map(([,text])=>({text}))}}
function ensureQuestions(){const needed=state.size**2;while(state.questions.length<needed){state.questions.push({text:'Add your question in Question studio.'})}state.questions=state.questions.slice(0,needed);state.claims=Array.from({length:needed},(_,i)=>state.claims[i]??null);state.attempts=Array.from({length:needed},(_,i)=>state.attempts?.[i]??null)}
function teamName(team=state.turn){return team===0?state.teamA:state.teamB}function score(t){return state.claims.filter(x=>x===t).length}
function setView(view){$$('.view').forEach(v=>v.classList.toggle('active',v.id===view));$$('.nav-link').forEach(b=>b.classList.toggle('active',b.dataset.view===view));render()}
function tile(i, readOnly=false){let c=state.claims[i],attempt=state.attempts[i],b=document.createElement('button');b.className=`tile ${c!==null?`claim-${c===0?'a':'b'}`:attempt!==null?`tried-${attempt===0?'a':'b'}`:''}`;b.disabled=readOnly||c!==null||state.finished;b.innerHTML=`<span class="tile-number">${String(i+1).padStart(2,'0')}</span>`;if(!readOnly)b.onclick=()=>openQuestion(i);return b}
function render(){ensureQuestions(); save();$('#team-a-name').textContent=state.teamA;$('#team-b-name').textContent=state.teamB;$('#team-a-score').textContent=score(0);$('#team-b-score').textContent=score(1);$('#turn-label').textContent=state.finished?'Match complete':`${teamName()}' turn`;$('#timer').textContent=state.seconds;$('#timer').className=`timer ${state.started?'running':''} ${state.seconds<=10&&state.started?'urgent':''}`;$('#game-status').textContent=state.finished?'Start a new game to play again.':state.started?`${teamName()} has ${state.seconds} seconds to answer.`:'Choose an unclaimed tile to start the clock.';let grid=$('#grid');grid.style.setProperty('--size',state.size);grid.replaceChildren(...state.questions.map((_,i)=>tile(i)));renderPlayers();renderSettings()}
function renderPlayers(){let grid=$('#player-grid');grid.style.setProperty('--size',state.size);grid.replaceChildren(...state.questions.map((_,i)=>tile(i,true)));$('#player-turn').textContent=state.finished?'Match complete':`${teamName()}' turn`;$('#player-timer').textContent=state.seconds;$('#player-a').textContent=`${state.teamA} · ${score(0)}`;$('#player-b').textContent=`${state.teamB} · ${score(1)}`;let q=state.selected!==null?state.questions[state.selected]:null;$('#player-question').textContent=q?q.text:'Select a square to reveal the question.'}
function renderSettings(){if(!$('#settings').classList.contains('active'))return;$('#input-team-a').value=state.teamA;$('#input-team-b').value=state.teamB;$('#input-size').value=state.size;$('#input-line').value=state.line;$('#question-count').textContent=`${state.questions.length} prompts`;let editor=$('#question-editor');editor.replaceChildren(...state.questions.map((q,i)=>{let d=document.createElement('article');d.className='question-card';d.innerHTML=`<header>SQUARE ${String(i+1).padStart(2,'0')}</header><label>Question<textarea data-key="text" maxlength="300">${esc(q.text)}</textarea></label>`;d.querySelector('[data-key]').oninput=e=>{state.questions[i].text=e.target.value;save();renderPlayers()};return d}))}
function esc(v=''){return v.replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;')}
function openQuestion(i){state.selected=i;state.seconds=30;state.started=true;clearInterval(interval);interval=setInterval(tick,1000);$('#modal-question').textContent=state.questions[i].text;$('#question-modal').showModal();render()}
function tick(){if(!state.started)return;state.seconds--;if(state.seconds<=0){state.seconds=0;stopTimer();$('#question-modal').close();state.selected=null;switchTurn('Time is up — square stays open.');}render()}
function stopTimer(){clearInterval(interval);state.started=false}
function switchTurn(message){state.turn=state.turn?0:1;state.seconds=30;state.selected=null;save();render();if(message)$('#game-status').textContent=message}
function hasLine(player){let n=state.size,k=Math.min(state.line,n),a=state.claims;for(let r=0;r<n;r++)for(let c=0;c<n;c++)for(const[dr,dc]of[[0,1],[1,0],[1,1],[1,-1]]){let endR=r+(k-1)*dr,endC=c+(k-1)*dc;if(endR>=0&&endR<n&&endC>=0&&endC<n&&Array.from({length:k},(_,z)=>a[(r+z*dr)*n+c+z*dc]===player).every(Boolean))return true}return false}
function declareWinner(winner,reason){stopTimer();state.finished=true;save();$('#winner-title').textContent=winner===null?'It’s a tie!':`${teamName(winner)} wins!`;$('#winner-copy').textContent=reason;$('#winner-modal').showModal();render()}
function resetGame(){stopTimer();state={...state,claims:Array(state.size**2).fill(null),attempts:Array(state.size**2).fill(null),turn:0,selected:null,seconds:30,started:false,finished:false};save();render()}
$('.topbar nav').onclick=e=>{if(e.target.dataset.view)setView(e.target.dataset.view)};$('.brand').onclick=e=>{if(e.currentTarget.dataset?.view)setView('play')};$('#new-game').onclick=resetGame;$('#start-timer').onclick=()=>{if(state.selected===null){$('#game-status').textContent='Select a tile first.';return}state.started=true;render()};$('#end-game').onclick=()=>{let a=score(0),b=score(1);declareWinner(a===b?null:a>b?0:1,`Final score: ${state.teamA} ${a} — ${b} ${state.teamB}.`)};
$('#modal-close').onclick=()=>{$('#question-modal').close();stopTimer();state.selected=null;render()};$('#incorrect').onclick=()=>{let p=state.turn;state.attempts[state.selected]=p;$('#question-modal').close();stopTimer();switchTurn('Unsuccessful attempt — the tile is marked and remains available.')};$('#correct').onclick=()=>{let p=state.turn;state.claims[state.selected]=p;$('#question-modal').close();stopTimer();if(hasLine(p))declareWinner(p,`${teamName(p)} connected ${state.line} squares in a row.`);else switchTurn('Correct — square claimed!')};$('#winner-new-game').onclick=()=>{$('#winner-modal').close();resetGame()};
$('#game-settings').onsubmit=e=>{e.preventDefault();state.teamA=$('#input-team-a').value.trim()||'Team 01';state.teamB=$('#input-team-b').value.trim()||'Team 02';state.size=+$('#input-size').value;state.line=Math.min(+$('#input-line').value,state.size);ensureQuestions();resetGame();setView('play')};$('#load-sample').onclick=async()=>{state.questions=await loadSharedQuestions();ensureQuestions();render()};$('#clear-claims').onclick=resetGame;
(async()=>{state=await load();state.questions=await loadSharedQuestions();ensureQuestions();render()})();

